name: Crear Nuevo Repositorio

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Nombre del nuevo repositorio (ejemplo: mi-nuevo-repo)'
        required: true
      branch_name:
        description: 'Nombre de la rama principal (ejemplo: main, develop)'
        required: true
        default: 'main'
      init_files:
        description: '¿Incluir archivos iniciales? (README, .gitignore, LICENSE)'
        type: choice
        options:
          - 'sí'
          - 'no'
        default: 'sí'

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Crear repositorio
        id: create
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_WITH_REPO_PERMISSION }}
        run: |
          REPO_NAME="${{ github.event.inputs.repo_name }}"
          BRANCH_NAME="${{ github.event.inputs.branch_name }}"
          INIT_FILES="${{ github.event.inputs.init_files }}"

          # Crear el repositorio
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/user/repos" \
            -d "{\"name\":\"$REPO_NAME\", \"private\":false, \"auto_init\":$INIT_FILES}")

          REPO_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "repo_url=$REPO_URL" >> $GITHUB_OUTPUT

          # Si se eligieron archivos iniciales, clonar y personalizar
          if [ "$INIT_FILES" = "sí" ]; then
            git clone "https://$GITHUB_TOKEN@github.com/${{ github.repository_owner }}/$REPO_NAME.git"
            cd "$REPO_NAME"
            git checkout -b "$BRANCH_NAME"
            echo "# $REPO_NAME" > README.md
            echo "*.log" > .gitignore
            echo "MIT License" > LICENSE
            git add .
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git commit -m "Añadir archivos iniciales"
            git push origin "$BRANCH_NAME"
            git push origin --delete main || true
          fi

      - name: Mostrar resultado
        run: |
          echo "Repositorio creado: ${{ steps.create.outputs.repo_url }}"
